return {
    FANCY = {
        StreakName = "Fancy",
        EIDName = "Fancy",
        CustomTag = "fancy",
        VanillaItems = {
            CollectibleType.COLLECTIBLE_PHD,
            CollectibleType.COLLECTIBLE_MIDAS_TOUCH,
            CollectibleType.COLLECTIBLE_EPIC_FETUS,
            CollectibleType.COLLECTIBLE_MORE_OPTIONS,
            CollectibleType.COLLECTIBLE_GOLDEN_RAZOR,
            CollectibleType.COLLECTIBLE_MEMBER_CARD,
            CollectibleType.COLLECTIBLE_MONEY_EQUALS_POWER,
            CollectibleType.COLLECTIBLE_PAGEANT_BOY,
            CollectibleType.COLLECTIBLE_STOP_WATCH,
            CollectibleType.COLLECTIBLE_BLACK_LOTUS,
            CollectibleType.COLLECTIBLE_TELEPORT_2,
            CollectibleType.COLLECTIBLE_MOMS_RING,
            CollectibleType.COLLECTIBLE_KING_BABY,
            CollectibleType.COLLECTIBLE_DOLLAR
        },
        NumReq = 3,
        Costume = Isaac.GetCostumeIdByPath("gfx_tb/characters/costume_fancy.anm2"),
    },
    HYDRA = {
        StreakName = "Hydra",
        EIDName = "Hydra",
        CustomTag = "head",
        VanillaItems = {
            CollectibleType.COLLECTIBLE_CRICKETS_HEAD,
            CollectibleType.COLLECTIBLE_TAMMYS_HEAD,
            CollectibleType.COLLECTIBLE_BOBS_ROTTEN_HEAD,
            CollectibleType.COLLECTIBLE_STEVEN,
            CollectibleType.COLLECTIBLE_GUPPYS_HEAD,
            CollectibleType.COLLECTIBLE_FATE,
            CollectibleType.COLLECTIBLE_GOAT_HEAD,
            CollectibleType.COLLECTIBLE_HEAD_OF_KRAMPUS,
            CollectibleType.COLLECTIBLE_GODHEAD,
            CollectibleType.COLLECTIBLE_SACK_HEAD,
            CollectibleType.COLLECTIBLE_HEAD_OF_THE_KEEPER,
            CollectibleType.COLLECTIBLE_CONE_HEAD,
            CollectibleType.COLLECTIBLE_VOODOO_HEAD,
            CollectibleType.COLLECTIBLE_BERSERK,
            CollectibleType.COLLECTIBLE_DECAP_ATTACK,
            CollectibleType.COLLECTIBLE_HOST_HAT,
            CollectibleType.COLLECTIBLE_2SPOOKY,
        },
        NumReq = 3,
        Costume = Isaac.GetCostumeIdByPath("gfx_tb/characters/costume_hydra.anm2"),
    },
}