local mod = MilcomMOD

local BASEDATA = {
    CONDENSED_MILK_BONUS = 1,
    NOSE_CANDY_STATBONUSES = {
        SPEED = 0,
        FIREDELAY = 0,
        DAMAGE = 0,
        RANGE = 0,
        SHOTSPEED = 0,
        LUCK = 0,
    },
    MAMMONS_OFFERING_BONUS = 0,
    MAMMONS_OFFERING_PERMABONUS = 0,
    LION_SKULL_MARKS = 0,
    BLOOD_RITUAL_DATA = {},
    CARAMEL_APPLE_DATA = {},
    PAINKILLERS_DAMAGE_COUNTER = 0,
    PAINKILLERS_DAMAGE_TIMER = 0,
    SIGIL_OF_GREED_CHARGE = 0,
}

return BASEDATA