local mod = MilcomMOD

local BASEDATA = {
    CONDENSED_MILK_BONUS = 1,
    NOSE_CANDY_STATBONUSES = {
        SPEED = 0,
        FIREDELAY = 0,
        DAMAGE = 0,
        RANGE = 0,
        SHOTSPEED = 0,
        LUCK = 0,
    },
    MAMMONS_OFFERING_BONUS = 0,
    MAMMONS_OFFERING_PERMABONUS = 0,
    LION_SKULL_MARKS = 0,
    BLOOD_RITUAL_DATA = {},
    CARAMEL_APPLE_DATA = {},
    PAINKILLERS_DAMAGE_COUNTER = 0,
    PAINKILLERS_DAMAGE_TIMER = 0,
    SIGIL_OF_GREED_CHARGE = 0,
    
    --! all the stupid pill shits i could've probably done with null items
    DYSLEXIA_DURATION = 0,
    DYSLEXIA_HORSE = false,
    BLEEEGH_HORSE = false,
    BLEEEGH_DURATION = 0,
    HEARTBURN_MODE = 0,
    COAGULANT_MODE = 0,
    ARTHRITIS_DURATION = 0,
    ARTHRITIS_HORSE = false,
    ARTHRITIS_CHOSEN_ANGLE = -1,
    ATROPHY_DURATION = 0,
    ATROPHY_MAXDURATION = 0,
    ATROPHY_HORSESTACKS = 0,
    VITAMINS_DURATION = 0,
    VITAMINS_HORSE = false,
    DAMAGE_UP_STACKS = 0,
    DAMAGE_DOWN_STACKS = 0,
}

return BASEDATA