-- misc
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_HORSE_TRANQUILIZER, function(d)
    return d:Unlocked(Achievement.HORSE_PILLS)
end)
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_WONDER_DRUG, function(d)
    return d:Unlocked(Achievement.HORSE_PILLS) and d:Unlocked(Achievement.GOLDEN_PILLS)
end)

-- atlas
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_ROCK_CANDY, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.BOSS_RUSH))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_SALTPETER, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.HUSH))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_ASCENSION, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.ISAAC))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_GLASS_VESSEL, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.BLUE_BABY))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_MISSING_PAGE_3, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.SATAN))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_BONE_BOY, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.LAMB))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_GILDED_APPLE, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.ULTRA_GREED))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_PRISMSTONE, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.ULTRA_GREED, Difficulty.DIFFICULTY_HARD))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_AMBER_FOSSIL, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.MOTHER))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_STEEL_SOUL, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.BEAST))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_HOSTILE_TAKEOVER, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.DELIRIUM))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_MANTLES, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_ATLAS_A, CompletionType.MEGA_SATAN))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_MIRACLE_MANTLE, ToyboxMod:allMarkCondition(ToyboxMod.PLAYER_ATLAS_A, Difficulty.DIFFICULTY_HARD))

-- jonas
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_JONAS_LOCK, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.BOSS_RUSH))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_ANTIBIOTICS, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.HUSH))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_DADS_PRESCRIPTION, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.ISAAC))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_FOOD_STAMPS, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.BLUE_BABY))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_DR_BUM, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.SATAN))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_CLOWN_PHD, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.LAMB))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_DRILL, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.ULTRA_GREED))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_FOIL_CARD, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.ULTRA_GREED, Difficulty.DIFFICULTY_HARD))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_CANDY_DISPENSER, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.MOTHER))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_JONAS_MASK, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.BEAST))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_GIANT_CAPSULE, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.DELIRIUM))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_PILLS, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_JONAS_A, CompletionType.MEGA_SATAN))
--ToyboxMod:addAchievement(???, ToyboxMod:allMarkCondition(ToyboxMod.PLAYER_JONAS_A, Difficulty.DIFFICULTY_HARD))

-- milcom
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_DELIVERY_BOX, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.BOSS_RUSH))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_OIL_PAINTING, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.HUSH))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_DIVIDED_JUSTICE, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.ISAAC))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_PAPER_PLATE, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.BLUE_BABY))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_MISPRINT, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.SATAN))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_ATHEISM, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.LAMB))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_GOLDEN_CALF, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.ULTRA_GREED))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_GREEN_APPLE, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.ULTRA_GREED, Difficulty.DIFFICULTY_HARD))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_EFFIGY, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.MOTHER))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_CUTOUT, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.BEAST))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_MALICE, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.DELIRIUM))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT_CHAMPIONS, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_MILCOM_A, CompletionType.MEGA_SATAN))
--ToyboxMod:addAchievement(???, ToyboxMod:allMarkCondition(ToyboxMod.PLAYER_MILCOM_A, Difficulty.DIFFICULTY_HARD))