ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.ROCK_CANDY, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.BOSS_RUSH))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.SALTPETER, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.HUSH))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.ASCENSION, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.ISAAC))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.GLASS_VESSEL, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.BLUE_BABY))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.MISSING_PAGE_3, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.SATAN))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.BONE_BOY, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.LAMB))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.GILDED_APPLE, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.ULTRA_GREED))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.PRISMSTONE, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.ULTRA_GREED, Difficulty.DIFFICULTY_HARD))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.AMBER_FOSSIL, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.MOTHER))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.STEEL_SOUL, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.BEAST))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.HOSTILE_TAKEOVER, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.DELIRIUM))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.MANTLES, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, CompletionType.MEGA_SATAN))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.MIRACLE_MANTLE, ToyboxMod:allMarkCondition(ToyboxMod.PLAYER_TYPE.ATLAS_A, Difficulty.DIFFICULTY_HARD))

ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.JONAS_LOCK, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.BOSS_RUSH))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.WONDER_DRUG, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.HUSH))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.DADS_PRESCRIPTION, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.ISAAC))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.CANDY_DISPENSER, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.BLUE_BABY))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.DR_BUM, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.SATAN))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.JONAS_MASK, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.LAMB))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.ANTIBIOTICS, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.ULTRA_GREED))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.FOIL_CARD, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.ULTRA_GREED, Difficulty.DIFFICULTY_HARD))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.HORSE_TRANQUILIZER, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.MOTHER))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.CLOWN_PHD, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.BEAST))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.GIANT_CAPSULE, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.DELIRIUM))
ToyboxMod:addAchievement(ToyboxMod.ACHIEVEMENT.PILLS, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, CompletionType.MEGA_SATAN))
--ToyboxMod:addAchievement(???, ToyboxMod:allMarkCondition(ToyboxMod.PLAYER_TYPE.JONAS_A, Difficulty.DIFFICULTY_HARD))

--[[
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.BOSS_RUSH))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.HUSH))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.ISAAC))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.BLUE_BABY))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.SATAN))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.LAMB))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.ULTRA_GREED))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.ULTRA_GREED, Difficulty.DIFFICULTY_HARD))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.MOTHER))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.BEAST))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.DELIRIUM))
ToyboxMod:addAchievement(???, ToyboxMod:completionMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, CompletionType.MEGA_SATAN))
ToyboxMod:addAchievement(???, ToyboxMod:allMarkCondition(ToyboxMod.PLAYER_TYPE.MILCOM_A, Difficulty.DIFFICULTY_HARD))
--]]