

local BASEDATA = {
    HAS_SEEN_YANNY = 0,
    IS_CONBOI = 0,

    BURNING_BASEMENT_CLEARS = 0,
    FLOODED_CAVES_CLEARS = 0,
    DANK_DEPTHS_CLEARS = 0,
    SCARRED_WOMB_CLEARS = 0,
}

return BASEDATA