ToyboxMod.CONFIG = {
    ALPHABETBOX_EID_DISPLAYS = 3,
    TINTED_ROOM_DISPLAY_TYPE = 0,

    CHAMPIONS_IN_GREED = true,

    MANTLE_WEIGHT = 0.5,
    MOD_CHAMPION_CHANCE = 0.05,

    GOOD_JUICE_LESSLAG = 0,

    MORE_STATS = false,
    EPIC_ITEM_MODE = 0,
    AWESOME_FUCKING_TITLESCREEN = true,
    DADS_SLIPPER_COLOR = Color(135/255, 150/255, 189/255, 1),
    SUPER_RETROFALL_BROS = false,
}