

local BASEDATA = {
    RAINBOW_KEY_ACTIVE = 0,

    DRILLDATA = {
        IS_ACTIVE = 0,
        ITEM_ID = 0,
        FORCE_SET_AMBUSH = 0,
        IGNORE_RESET_DATA = 0,
    },
    DRILL_PREIDX = 83,

    PREFERRED_OPTIONS_LASTITEM = CollectibleType.COLLECTIBLE_BREAKFAST,
    PREFERRED_OPTIONS_LASTPRICE = 0,
    PREFERRED_OPTIONS_TOOKITEM = 0,
    PREFERRED_OPTIONS_MARKROOMFORCLEAR = -1,

    CUSTOM_PILL_POOL = 0,
    PILLS_TOTAL = 0,
    PILLS_GOOD = 0,
    PILLS_NEUTRAL = 0,
    PILLS_BAD = 0,
    PILL_COLORS = 0,
    PILL_TABLES_CALCULATED = 0,
    PILLS_BAD_NUM = 0,
    PILLS_GOOD_NUM = 0,
    PILLS_NEUTRAL_NUM = 0,

    MILCOM_COINS = 0,
    MILCOM_KEYS = 0,
    MILCOM_BOMBS = 0,

    BIGBLIND_INDEXES = {[0]=0},
    BIGBLIND_FINALSTR = {[0]=0},
    BIGBLIND_CONBOI_ACTIVE = 0,

    QUAKEBOMBS_GRIDS = {},

    FOILCARD_VALUE = 0,
    MANTLEDARK_USES = 0,

    MATTMAN_CHANCE_LAMB_KILLS = 0,

    EQUALIZER_PICKUP = "",
    EQUALIZER_STAT = "",
    EQUALIZER_COINS = 0,
    EQUALIZER_KEYS = 0,
    EQUALIZER_BOMBS = 0,

    TINTED_ROOM_POSITIONS = {}
}

return BASEDATA