local t = {
    --PASSIVES
    -- "scripts_toybox.items.passives.",
    "scripts_toybox.items.passives.coconut_oil",
    "scripts_toybox.items.passives.goat_milk",
    "scripts_toybox.items.passives.condensed_milk",
    "scripts_toybox.items.passives.nose_candy",
    "scripts_toybox.items.passives.lion_skull",
    "scripts_toybox.items.passives.caramel_apple",
    "scripts_toybox.items.passives.painkillers",
    "scripts_toybox.items.passives.tech_ix",
    "scripts_toybox.items.passives.fatal_signal",
    "scripts_toybox.items.passives.pepper_x",
    "scripts_toybox.items.passives.meteor_shower",
    "scripts_toybox.items.passives.blessed_ring",
    "scripts_toybox.items.passives.eyestrain",
    "scripts_toybox.items.passives.4_4",
    "scripts_toybox.items.passives.evil_rock",
    "scripts_toybox.items.passives.onyx",
    "scripts_toybox.items.passives.sigil_of_greed",
    "scripts_toybox.items.passives.dads_prescription",
    "scripts_toybox.items.passives.horse_tranquilizer",
    "scripts_toybox.items.passives.silk_bag",
    "scripts_toybox.items.passives.rock_candy",
    "scripts_toybox.items.passives.missing_page_3",
    "scripts_toybox.items.passives.glass_vessel",
    "scripts_toybox.items.passives.bone_boy",
    "scripts_toybox.items.passives.steel_soul",
    "scripts_toybox.items.passives.bobs_heart",
    "scripts_toybox.items.passives.clown_phd",
    "scripts_toybox.items.passives.giant_capsule",
    "scripts_toybox.items.passives.jonas_mask",
    "scripts_toybox.items.passives.love_letter",
    "scripts_toybox.items.passives.quake_bombs",
    "scripts_toybox.items.passives.atheism",
    "scripts_toybox.items.passives.mayonnaise",
    "scripts_toybox.items.passives.awesome_fruit",
    "scripts_toybox.items.passives.bloody_map",
    "scripts_toybox.items.passives.saltpeter",
    "scripts_toybox.items.passives.dr_bum",
    "scripts_toybox.items.passives.preferred_options",
    "scripts_toybox.items.passives.plasma_globe",
    "scripts_toybox.items.passives.blessed_bombs",
    "scripts_toybox.items.passives.cursed_eulogy",
    "scripts_toybox.items.passives.haemorrhage",
    "scripts_toybox.items.passives.fish",
    "scripts_toybox.items.passives.bobs_thesis", -- Also includes Placeholder
    "scripts_toybox.items.passives.asteroid_belt",
    "scripts_toybox.items.passives.barbed_wire",
    "scripts_toybox.items.passives.coffee_cup",
    "scripts_toybox.items.passives.conjunctivitis",
    "scripts_toybox.items.passives.dads_slipper",
    "scripts_toybox.items.passives.food_stamps",
    "scripts_toybox.items.passives.golden_calf",
    "scripts_toybox.items.passives.last_beer",
    "scripts_toybox.items.passives.retrofall",
    "scripts_toybox.items.passives.brunch",
    "scripts_toybox.items.passives.toast",
    "scripts_toybox.items.passives.lucky_pebbles",
    "scripts_toybox.items.passives.finger_trap",
    "scripts_toybox.items.passives.hemolymph",

    "scripts_toybox.items.passives.the_elder_scroll", -- just the shader fo now

    --ACTIVES
    -- "scripts_toybox.items.actives.",
    "scripts_toybox.items.actives.pliers",
    "scripts_toybox.items.actives.blood_ritual",
    "scripts_toybox.items.actives.sunk_costs",
    "scripts_toybox.items.actives.bronze_bull",
    "scripts_toybox.items.actives.ascension",
    "scripts_toybox.items.actives.gilded_apple",
    "scripts_toybox.items.actives.drill",
    "scripts_toybox.items.actives.d",
    "scripts_toybox.items.actives.pez_dispenser",
    "scripts_toybox.items.actives.alphabet_box",
    "scripts_toybox.items.actives.hostile_takeover",
    "scripts_toybox.items.actives.bloody_whistle",
    "scripts_toybox.items.actives.art_of_war",
    "scripts_toybox.items.actives.big_bang",
    "scripts_toybox.items.actives.chocolate_bar",
    "scripts_toybox.items.actives.exoricsm_kit",
    "scripts_toybox.items.actives.delivery_box",
    "scripts_toybox.items.actives.moms_photobook",

    --TRINKETS
    -- "scripts_toybox.items.trinkets.",
    "scripts_toybox.items.trinkets.wonder_drug",
    "scripts_toybox.items.trinkets.antibiotics",
    "scripts_toybox.items.trinkets.amber_fossil",
    "scripts_toybox.items.trinkets.sine_worm",
    "scripts_toybox.items.trinkets.big_blind",
    "scripts_toybox.items.trinkets.jonas_lock",
    "scripts_toybox.items.trinkets.big_boy_bathwater",
    "scripts_toybox.items.trinkets.black_rune_shard",
    "scripts_toybox.items.trinkets.suppository",
    "scripts_toybox.items.trinkets.divided_justice",
    "scripts_toybox.items.trinkets.killscreen",
    "scripts_toybox.items.trinkets.mirror_shard",
    "scripts_toybox.items.trinkets.lucky_tooth",

    --UNUSED
    --"scripts_toybox.items.actives.btrain",
    --"scripts_toybox.items.unused.laser_pointer",
    --"scripts_toybox.items.unused.scattered_tome",
    --"scripts_toybox.items.unused.toy_gun",
    --"scripts_toybox.items.unused.foam_bullet",
    --"scripts_toybox.items.unused.malicious_brain",
    --"scripts_toybox.items.unused.limit_break",

    --JOKE
    "scripts_toybox.items.troll.equalizer",
    "scripts_toybox.items.troll.golden_prayer_card",
    "scripts_toybox.items.troll.golden_schoolbag",
    "scripts_toybox.items.troll.catharsis",
    "scripts_toybox.items.troll.uranium",
    "scripts_toybox.items.troll.voodoo_doll",
}
for _, path in ipairs(t) do
    include(path)
end