

local ITEMS = {
    [ToyboxMod.COLLECTIBLE_COCONUT_OIL] =         "Tears up + speed down + slippery movement",
    [ToyboxMod.COLLECTIBLE_CONDENSED_MILK] =      "Tears multiplier + DMG becomes tears",
    [ToyboxMod.COLLECTIBLE_EYESTRAIN] =           "DMG + luck up",
    [ToyboxMod.COLLECTIBLE_GOAT_MILK] =           "Tears up + random tear delay",
    [ToyboxMod.COLLECTIBLE_PLIERS] =              "Self harm for tears up for the room",
    [ToyboxMod.COLLECTIBLE_SUNK_COSTS] =          "5 coins + spend coins for tears up for the room",
    [ToyboxMod.COLLECTIBLE_NOSE_CANDY] =          "On floor entry (speed up + random stat up + random stat down)",
    [ToyboxMod.COLLECTIBLE_LION_SKULL] =          "DMG up on room clear + DMG down when hurt",
    [ToyboxMod.COLLECTIBLE_BLOOD_RITUAL] =        "Gain 3 evil familiars for the room",
    [ToyboxMod.COLLECTIBLE_TECH_IX] =             "Orbital laser ring while firing",
    [ToyboxMod.COLLECTIBLE_PAINKILLERS] =         "No i-frames + may become invulnerable when hurt",
    [ToyboxMod.COLLECTIBLE_SILK_BAG] =            "Gives on-command invulnerability every few rooms",
    [ToyboxMod.COLLECTIBLE_METEOR_SHOWER] =       "Meteor strikes in hostile rooms",
    [ToyboxMod.COLLECTIBLE_BLESSED_RING] =        "Beams of light occasionally strike enemies",
    [ToyboxMod.COLLECTIBLE_GILDED_APPLE] =        "Gain a golden heart",
    [ToyboxMod.COLLECTIBLE_DADS_PRESCRIPTION] =   "A pill appears in special rooms",
    [ToyboxMod.COLLECTIBLE_HORSE_TRANQUILIZER] =  "Consume a pill when you get an item",
    [ToyboxMod.COLLECTIBLE_BOBS_HEART] =          "Blast immunity + (poison + may explode) when hurt",
    [ToyboxMod.COLLECTIBLE_GLASS_VESSEL] =        "Nullify damage + refill with red hearts",
    [ToyboxMod.COLLECTIBLE_BONE_BOY] =            "Immortal bony buddy",
    [ToyboxMod.COLLECTIBLE_HOSTILE_TAKEOVER] =    "(Temporary all stats up + refill on kill) for the room",
    [ToyboxMod.COLLECTIBLE_STEEL_SOUL] =          "Soul / black hearts can take an extra hit",
    [ToyboxMod.COLLECTIBLE_ROCK_CANDY] =          "Tears + shotspeed up + random mantle",
    [ToyboxMod.COLLECTIBLE_GIANT_CAPSULE] =       "Temporary virus buddy when using consumables",
    [ToyboxMod.COLLECTIBLE_PEZ_DISPENSER] =       "Consumable inventory",
    [ToyboxMod.COLLECTIBLE_MISSING_PAGE_3] =      "Enemies may (be skull champions + drop a black heart)",
    [ToyboxMod.COLLECTIBLE_ASCENSION] =           "Temporary flight",
    [ToyboxMod.COLLECTIBLE_4_4] =           "Double-tap stunning-tear wave + tears may glitch enemies",
    [ToyboxMod.COLLECTIBLE_DR_BUM] =              "Cards-for-pills buddy",
    [ToyboxMod.COLLECTIBLE_JONAS_MASK] =          "Shadow buddy that changes on floor entry",
    [ToyboxMod.COLLECTIBLE_CLOWN_PHD] =           "Better pills + random pills",
    [ToyboxMod.COLLECTIBLE_ALPHABET_BOX] =        "Reroll items into next one alphabetically",
    [ToyboxMod.COLLECTIBLE_LOVE_LETTER] =         "Tears may charm + charmed enemies are safer and weaker",
    [ToyboxMod.COLLECTIBLE_QUAKE_BOMBS] =         "5 bombs + quaking blast + more drops from rocks",
    [ToyboxMod.COLLECTIBLE_ATHEISM] =             "Devil / Angel Rooms are Treasure Rooms",
    [ToyboxMod.COLLECTIBLE_MAYONAISE] =           "Shotspeed up + 1 eternal heart",
    [ToyboxMod.COLLECTIBLE_AWESOME_FRUIT] =       "HP up + heal + progress to all transformations",
    [ToyboxMod.COLLECTIBLE_SALTPETER] =           "Deal AOE damage + may fire an explosive tear",
    [ToyboxMod.COLLECTIBLE_PLASMA_GLOBE] =        "Tears zap enemies while flying",
    [ToyboxMod.COLLECTIBLE_CURSED_EULOGY] =       "Items may be cursed + 1 black heart",
    [ToyboxMod.COLLECTIBLE_BLESSED_BOMBS] =       "5 bombs + holy aura bombs + bombs explode slower",
    [ToyboxMod.COLLECTIBLE_D] =                   "Add or remove time from timer",
    [ToyboxMod.COLLECTIBLE_BLOODY_WHISTLE] =      "Drop bubbling blood creep",
    [ToyboxMod.COLLECTIBLE_HEMORRHAGE] =          "1 bone heart + tears up when hurt",
    [ToyboxMod.COLLECTIBLE_FISH] =                "Double insects + blue insects when hurt",
    [ToyboxMod.COLLECTIBLE_BOBS_THESIS] =         "Items turn into ‘All stats up’ for 1 stage",
    [ToyboxMod.COLLECTIBLE_PLACEHOLDER] =         "All stats up + morphs next stage",
    [ToyboxMod.COLLECTIBLE_ART_OF_WAR] =          "Random tear replacement for the room",
    [ToyboxMod.COLLECTIBLE_ASTEROID_BELT] =       "Defensive rock orbitals",
    [ToyboxMod.COLLECTIBLE_BARBED_WIRE] =         "Nearby enemy shots hurt their shooter",
    [ToyboxMod.COLLECTIBLE_BIG_BANG] =            "Resets itempools",
    [ToyboxMod.COLLECTIBLE_COFFEE_CUP] =          "Speed up + tears up",
    [ToyboxMod.COLLECTIBLE_LAST_BEER] =           "May shoot extra tears on kill per room",
    [ToyboxMod.COLLECTIBLE_CHOCOLATE_BAR] =       "HP up for the room",
    [ToyboxMod.COLLECTIBLE_CONJUNCTIVITIS] =      "(DMG up + shotspeed down + poison) for right eye",
    [ToyboxMod.COLLECTIBLE_FOOD_STAMPS] =         "Future items give HP",
    [ToyboxMod.COLLECTIBLE_GOLDEN_CALF] =         "Enemies may come back friendly",
    [ToyboxMod.COLLECTIBLE_RETROFALL] =           "Actives are dicey",
    [ToyboxMod.COLLECTIBLE_BRUNCH] =              "HP up + heal",
    [ToyboxMod.COLLECTIBLE_TOAST] =               "HP up + heal",
    [ToyboxMod.COLLECTIBLE_DELIVERY_BOX] =        "Spend coins for bomb or key",
    [ToyboxMod.COLLECTIBLE_CARAMEL_APPLE] =       "HP up + hearts may be doubled",

    [ToyboxMod.COLLECTIBLE_PORTABLE_TELLER] =     "Use coins for a chance to drop pickups",
}

local TRINKETS = {
    [ToyboxMod.TRINKET_ANTIBIOTICS] =             "Pills may be used twice",
    [ToyboxMod.TRINKET_WONDER_DRUG] =             "More common gold pills and horse pills",
    [ToyboxMod.TRINKET_AMBER_FOSSIL] =            "Blue flies may be locusts",
    [ToyboxMod.TRINKET_JONAS_LOCK] =              "Pills give a random stat up",
    [ToyboxMod.TRINKET_BIG_BLIND] =               "Enemies may drop coins when hurt",
    [ToyboxMod.TRINKET_BATH_WATER] =              "Damaging creep puddle when hurt",
    [ToyboxMod.TRINKET_BLACK_RUNE_SHARD] =        "Blue insects may be coins",
    [ToyboxMod.TRINKET_SUPPOSITORY] =             "Poops may drop pills",
    [ToyboxMod.TRINKET_DIVIDED_JUSTICE] =         "Pickups may give one of everything",
}

return {
    ["ITEMS"] = ITEMS,
    ["TRINKETS"] = TRINKETS,
}