ToyboxMod.CALLBACK_BOMBS_FIRED = {}

include("scripts_toybox.custom.callbacks.post_player_bomb_detonate")
include("scripts_toybox.custom.callbacks.post_player_double_tap")
include("scripts_toybox.custom.callbacks.post_player_attack")
include("scripts_toybox.custom.callbacks.use_active_item")
include("scripts_toybox.custom.callbacks.reset_ludovico_data")
include("scripts_toybox.custom.callbacks.copy_scatter_bomb_data")
include("scripts_toybox.custom.callbacks.post_fire_tear")
include("scripts_toybox.custom.callbacks.post_fire_bomb")
include("scripts_toybox.custom.callbacks.post_player_extra_dmg")
include("scripts_toybox.custom.callbacks.post_fire_aquarius")
include("scripts_toybox.custom.callbacks.post_fire_rocket")
include("scripts_toybox.custom.callbacks.post_new_room")
include("scripts_toybox.custom.callbacks.post_room_clear")
include("scripts_toybox.custom.callbacks.post_custom_champion_death")
include("scripts_toybox.custom.callbacks.post_poop_destroy")
include("scripts_toybox.custom.callbacks.poop_spawn_drop")